### ISSUE TITLE
UNIQUE constraint failed: e2074_post.slug

### ISSUE THREAD

**Issue by MegaMind98** [NepalGov/ElectionPortal#18]
Watch this, @InfoDevkota

**Comment by InfoDevkota** [comment]
Is it while you trying to add post? If so it is because the slug is already taken just add any int variable at last in a slug. if solved close the issue. else I will go through.

**Comment by InfoDevkota** [comment]
If its while migration. Just remove the unique=true in slug of post.(models.py) update older post slug to unique then you can make unique=true in slug again.

**Comment by MegaMind98** [comment]
I figured it out. Thanks, @InfoDevkota
