### ISSUE TITLE
Negative countdown

### ISSUE THREAD

**Issue by rameshsyn** [NepalGov/ElectionPortal#21]
Local election countdown is shown in negative.
![negative](https://user-images.githubusercontent.com/10565954/27429859-5a3b8a20-5766-11e7-8c47-55c34dce4e3c.PNG)

**Comment by MegaMind98** [comment]
Hi Ramesh, 

I believe we fixed it with this commit: [2f5092b ](https://github.com/NepalGov/ElectionPortal/commit/2f5092b030b572f143eca87b14492e0b10bd8f9a). Thank you for the note @rameshsyn!
